config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    resources :payments do
      member do
        get "payment_qrcode"
        get "confirm_payment"
        get "reject_payment"
      end
    end
  end

  resources :users do
    resources :wallets
  end

  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :payments
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :item
end

app/models/qrcode.rb
class Qrcode < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :wallets
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  after_action :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected

  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = Item.all
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!

  def create
    payment = Payment.new
    payment.item_id = params[:item_id]
    payment.type_payment = params[:commit]
    payment.user_id = current_user.id
    payment.amount = params[:amount]
    payment.status = "request"
    payment.save
    redirect_to item_payment_path(item_id: payment.item_id, id: payment.id)
  end

  def show
    payment = Payment.find(params[:id])
    timestamp = ServerTime.now
    token = Digest::MD5.hexdigest(generate_info(payment, timestamp.to_i.to_s))
    payment.update_attributes(token_created_at: timestamp)
    infor = "#{request.original_url}/payment_qrcode?token=#{token}"
    puts infor
    @qr = RQRCode::QRCode.new(infor)
      .as_png.resize(500, 500)
      .to_data_url
  end

  def payment_qrcode
    payment = Payment.where(id: params[:id], user_id: current_user.id)
    payment = payment.where.not(status: ["success", "reject"]).first
    return render "token_invalid" if !payment.present?
    if !token_expired(payment.token_created_at) &&
      check_valid_token(payment, params[:token])
      @target_payment = payment
      render "payment_qrcode"
    else
      render "token_invalid"
    end
  end

  def confirm_payment
    payment = Payment.find(params[:id])
    item = payment.item
    if token_expired(payment.token_created_at)
      @error = "Token expired"
    else
      my_wallet = current_user.wallets.first
      if !my_wallet.present?
        @error = "My wallet is blank. Please input money"
        return render "payment_complete"
      end
      new_cash = my_wallet.cash - payment.amount * payment.item.unit_price
      if new_cash < 0
        @error = "Your wallet does not have enough money"
        return render "payment_complete"
      end
      new_amount_item = item.amount - payment.amount
      ActiveRecord::Base.transaction do
        my_wallet.update_attributes(cash: new_cash)
        payment.update_attributes(status: "success")
        item.update_attributes(amount: new_amount_item)
        @success = "Payment Complete!!"
      end
    end
    render "payment_complete"
  rescue ActiveRecord::RecordInvalid
    @error = "Payment Not Complete"
    render "payment_complete"
  end

  def reject_payment
    payment = Payment.find(params[:id])
    payment.update_column(:status, "reject")
    redirect_to root_path
  end

  private
  def generate_info payment, timestamp
    infor = current_user.email + payment.item.name + payment.amount.to_s
      + payment.item.unit_price.to_s + timestamp
    infor
  end

  def check_valid_token payment, token
    infor = current_user.email + payment.item.name + payment.amount.to_s
      + payment.item.unit_price.to_s + payment.token_created_at.to_i.to_s
    Digest::MD5.hexdigest(infor) == token
  end

  def token_expired token_created_at
    (ServerTime.now - token_created_at) > 5.minutes
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :authenticate_user!
  def index
    @my_wallet = Wallet.find_by(user_id: params[:user_id])
  end

  def new
    @wallet = Wallet.new
  end

  def create
    @wallet = Wallet.new wallet_params
    @wallet.user_id = current_user.id
    @wallet.save
    redirect_to user_wallets_path(current_user.id)
  end

  private
  def wallet_params
    params.require(:wallet).permit :cash, :card_name, :card_number
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generate_qrcodes_helper.rb
module GenerateQrcodesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def generate_qrcode item
    RQRCode::QRCode.new(create_infor_qrcode(item))
      .as_png.resize(300, 300)
      .to_data_url
  end

  def create_infor_qrcode item
    "Tên sản phẩm: #{item.name} \n" +
    "Số lượng: #{item.amount} \n" +
    "Đơn giá: #{item.unit_price}"
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/items/index.html.erb
<div class="row">
  <% @items.each do |item| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= image_tag item.image, alt: item.name, style: "width: 300px; height: 300px" %>
        <div class="caption">
          <h3>
            <%= item.name %>
            <span class="badge"><%= item.amount %></span>
          </h3>
          <p><%= item.infor %></p>
          <p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter<%= item.id %>">
              Mua
            </button>
            <a href="#" class="btn btn-default" role="button">Chi tiết</a>
          </p>
          <div class="modal fade" id="exampleModalCenter<%= item.id %>"
            tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title text-center text-uppercase"
                    id="exampleModalLongTitle">
                    CHI TIẾT ĐƠN HÀNG
                  </h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <%= form_with url: item_payments_path(item.id), local: true do |form| %>
                  <div class="modal-body">
                    <label>Số lượng</label>
                    <%= form.text_field :amount, class: "form-control" %>
                  </div>
                  <div class="modal-footer">
                    <%= form.submit "QRCode Payment", class: "btn btn-primary",
                      name: "commit", value: "qrcodepay" %>
                    <%= form.submit "Normal Payment", class: "btn btn-success",
                      name: "commit", value: "normalpay" %>
                    <button type="button" class="btn btn-secondary"
                      data-dismiss="modal">
                      Close
                    </button>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">QrPay Demo</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "Home", items_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if current_user.present? %>
              <%= current_user.email %>
            <% else %>
              Action
            <% end %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% if current_user %>
              <li>
                <%= link_to 'Logout', destroy_user_session_path, method: 'DELETE' %>
              </li>
              <li>
                <%= link_to 'My Wallet', user_wallets_path(current_user.id) %>
              </li>
            <% else %>
              <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QrCodeDemo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body ng-app="qrCodeApp" ng-strict-di>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/payments/payment_complete.html.erb
<div class="container">
  <div class="row text-center">
    <% if !@error.nil? %>
      <h2 class="text-danger"><strong><%= @error %></strong></h2>
    <% end %>
    <% if !@success.nil? %>
      <h2 class="text-success"><strong><%= @success %></strong></h2>
    <% end %>
  </div>
</div>

app/views/payments/payment_qrcode.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="text-center">
                <i class="fa fa-search-plus pull-left icon"></i>
                <h2 class="text-uppercase text-primary">
                  <strong>Chi tiết đơn hàng</strong>
                </h2>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-12 col-md-4 col-lg-4 pull-left">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Billing Details</div>
                        <div class="panel-body">
                            <strong>Email:</strong><br>
                            <%= current_user.email %><br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-4 col-lg-4">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Payment Information</div>
                        <div class="panel-body">
                            <strong>Card Name:</strong>
                            <%= current_user.wallets.first.card_name if current_user.wallets.present? %>
                            <br>
                            <strong>Card Number:</strong>
                            <%= current_user.wallets.first.card_number if current_user.wallets.present? %>
                            <br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-4 col-lg-4">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Order Preferences</div>
                        <div class="panel-body">
                            <strong>Gift:</strong> No<br>
                            <strong>Express Delivery:</strong> Yes<br>
                            <strong>Insurance:</strong> No<br>
                            <strong>Coupon:</strong> No<br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="text-center">
                      <strong class="text-primary">Order summary</strong>
                    </h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <td><strong>Item Name</strong></td>
                                    <td class="text-center"><strong>Item Price</strong></td>
                                    <td class="text-center"><strong>Item Quantity</strong></td>
                                    <td class="text-right"><strong>Total</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><%= @target_payment.item.name %></td>
                                    <td class="text-center">
                                      <%= @target_payment.item.unit_price %> VND
                                    </td>
                                    <td class="text-center">
                                      <%= @target_payment.amount %>
                                    </td>
                                    <td class="text-right">
                                      <%= @target_payment.amount * @target_payment.item.unit_price %> VND
                                    </td>
                                </tr>
                                <tr>
                                    <td class="emptyrow"><i class="fa fa-barcode iconbig"></i></td>
                                    <td class="emptyrow"></td>
                                    <td class="emptyrow text-center"><strong>Total</strong></td>
                                    <td class="emptyrow text-right">
                                      <%= @target_payment.amount * @target_payment.item.unit_price %> VND
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="pull-right">
          <%= link_to "Confirm", confirm_payment_item_payment_path(@target_payment.item_id, @target_payment.id),
            class: "btn btn-success" %>
          <%= link_to "Reject", reject_payment_item_payment_path(@target_payment.item_id, @target_payment.id),class: "btn btn-danger" %>
        </div>
      </div>
    </div>
</div>

app/views/payments/show.html.erb
<div class="container">
  <div class="row text-center">
    <h3 class="text-danger">Please Scan QRCode Below With My Phone</h3>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="qr_code text-center">
        <%= image_tag @qr %>
      </div>
    </div>
  </div>
</div>

app/views/payments/token_invalid.html.erb
<div class="bdfill">
  <div class="lol">
    <%= image_tag("lol.gif", alt: "lol") =%>
    <br><br>
    Token invalid or expired
    <br>
    Please generate new QrCode Payment
  </div>
</div>

app/views/wallets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <% if !@my_wallet.present? %>
        <div class="jumbotron">
          <h1>My Wallet is blank</h1>
          <p>
            <%= link_to "New Wallet", new_user_wallet_path(current_user.id),
              class: "btn btn-primary btn-lg", role: "button" %>
          </p>
        </div>
      <% else %>
        <h1>
          <strong class="text-success">
            <%= @my_wallet.card_name %>
          </strong>
        <h1>
        <p>
          <strong>Cash: </strong>
          <%= @my_wallet.cash %>
        </p>
        <p>
          <strong>Card Number: </strong>
          <%= @my_wallet.card_number %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/wallets/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= form_for @wallet, url: user_wallets_path(current_user.id) do |f| %>
        <div class="form-group">
          <label>Dash</label>
          <%= f.text_field :cash, class: "form-control", placeholder: "Dash" %>
        </div>
        <div class="form-group">
          <label>Card Name</label>
          <%= f.text_field :card_name, class: "form-control", placeholder:"Card Name" %>
        </div>
        <div class="form-group">
          <label>Card Number</label>
          <%= f.text_field :card_number, class: "form-control", placeholder: "Card Number" %>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
      <% end %>
    </div>
  </div>
</div>